import { ArrowRight, BarChart3, Code2, Gauge, History, Languages, ShieldCheck, Sparkles, Timer } from 'lucide-react';
import { Link } from 'react-router-dom';

const features = [
  [Sparkles, 'Random code snippets', 'Fresh challenges generated locally from an open-source code generator.'],
  [Languages, 'Language-specific practice', 'Choose from the language keys exposed by the random-code package.'],
  [Gauge, 'Speed + accuracy', 'Track correct WPM, raw WPM, errors, accuracy, and completion time live.'],
  [History, 'Local progress history', 'Your race history and stats stay in browser LocalStorage — no account required.'],
];

export default function Home() {
  return <div className="coderush-grid relative overflow-hidden"><div className="pointer-events-none absolute left-1/2 top-0 h-[520px] w-[900px] -translate-x-1/2 bg-[radial-gradient(ellipse,rgba(34,211,238,.11),transparent_65%)]"/><main className="relative mx-auto max-w-7xl px-4 pb-20 pt-16 sm:px-6 sm:pt-24">
    <section className="max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/10 bg-cyan-300/[0.05] px-3 py-1.5 text-xs font-medium text-cyan-200"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400"/>100% local · no accounts · no backend</div><h1 className="text-5xl font-extrabold tracking-[-0.04em] text-white sm:text-7xl">Type code.<br/><span className="bg-gradient-to-r from-cyan-300 via-cyan-200 to-violet-300 bg-clip-text text-transparent">Improve your speed.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">CodeRush turns typing practice into a developer skill drill. Get a random code snippet, type it exactly, and build speed without sacrificing accuracy.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/practice" className="btn-primary">Start practice <ArrowRight size={18}/></Link><Link to="/history" className="btn-secondary">View your stats <BarChart3 size={18}/></Link></div></section>
    <section className="mt-20 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,copy])=><div className="panel p-5" key={title}><div className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Icon size={19}/></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{copy}</p></div>)}</section>
    <section className="mt-16 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="panel overflow-hidden p-6 sm:p-8"><div className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-slate-600"><Code2 size={15}/>How it works</div><div className="mt-6 grid gap-6 sm:grid-cols-3">{[['01','Choose','Language, length, difficulty.'],['02','Type','Match every character, space and line break.'],['03','Review','See WPM, accuracy and your local history.']].map(([num,title,copy])=><div key={num}><div className="font-mono text-xs text-cyan-300">{num}</div><h3 className="mt-2 font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{copy}</p></div>)}</div></div><div className="panel p-6 sm:p-8"><div className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-slate-600"><ShieldCheck size={15}/>Private by design</div><h3 className="mt-5 text-xl font-semibold">No server needed.</h3><p className="mt-2 text-sm leading-6 text-slate-500">Snippets are generated in the browser. Results and preferences are stored only in your browser’s LocalStorage.</p><div className="mt-6 flex items-center gap-4 text-xs text-slate-600"><span className="inline-flex items-center gap-1.5"><Timer size={14}/> Real-time metrics</span><span className="inline-flex items-center gap-1.5"><Code2 size={14}/> Code-first UI</span></div></div></section>
  </main></div>;
}
